### ISSUE TITLE
Mavenize or release with Nodeclipse train

### ISSUE THREAD

**Issue by paulvi** [gildur/SimplePropertiesEditor#1]
Hi Piotr

Just by chance noticed this plugin on Marketplace.
Could you please mavenize to add updates, see examples https://github.com/basti1302/startexplorer/ or https://github.com/nodeclipse/nodeclipse-1/

Other option is to add to Nodeclipse-1 repository https://github.com/nodeclipse/nodeclipse-1/, this way it will be released every month (no mater how many changes there were).

**Comment by gildur** [comment]
I've created update site for the plugin. Should be enough for now.
