### ISSUE TITLE
Please add README

### ISSUE THREAD

**Issue by paulvi** [gildur/SimplePropertiesEditor#2]

**Comment by paulvi** [comment]
Also http://marketplace.eclipse.org/content/simplepropertieseditor lacks Install button (MPC support)

**Comment by gildur** [comment]
I've added README and update site.

**Comment by paulvi** [comment]
http://marketplace.eclipse.org/content/simplepropertieseditor lacks Install button (MPC support)

please specify feature ID

**Comment by gildur** [comment]
Thanks for the info. I've added feature id to marketplace.
